### ISSUE TITLE
Toggle inline diff of file under the cursor

### ISSUE THREAD

**Issue by ruicsh** [Henrik-St/vscode-fugitive#1]
hey, using `vscode.neovim` and `vscode-fugitive`, I can't toggle an inline diff with the `=` keymap. Is this possible in VSCode? Maybe I can help.

**Comment by Henrik-St** [comment]
Hey, 
Feel free to open a pull request. 
Whether it is possible, i dont know yet. 
The vscode git api can be found here: 
https://github.com/microsoft/vscode/blob/main/extensions/git/src/api/git.d.ts
