### ISSUE TITLE
`g?` not opening help

### ISSUE THREAD

**Issue by YouRik** [Henrik-St/vscode-fugitive#6]
For me, `g?` on the fugitive page does not open the help.

All other mappings I tested work fine.
When I press `g?` the statusline says "The key combination (G, ⇧/) is not a command.

**Comment by Henrik-St** [comment]
Thank you for your issue report!
The vscode API currently has limited support for keyboard layout agnostic keymaps.
I am using QWERTZ.
I will add some information regarding this problem in the readme.
I might publish a copy of this extension for QWERTY.

A quick fix for you is remapping the command in the settings or adding the following to your keyboard.json


{
	"command": "fugitive.help",
	"key": "g shift+/",
	"when": "(vim.mode == 'Normal' || !vim.mode) && resourceScheme == fugitive && editorTextFocus"
}

**Comment by YouRik** [comment]
Thanks for the reply!
Yes that makes sense and remapping the shortcut works.

I think re-publishing for QWERTY would be excessive and not the right solution, as people might mix them up, or even have issues with other keyboard layouts (specifically DVORAK comes to mind).
Just a simple note in the readme detailing the remap for fugitive help, or potentially reacting to both (G, ?) and (G, ⇧/) by default would be a more sensible approach, in my opinion.

Either way, thanks for the help, I really enjoy this extension.
If you'd like more input, feel free to ask. Otherwise this issue may be closed.
